### ISSUE TITLE
Group allocation for additional rounds

### ISSUE THREAD

**Issue by simonkellly** [jonatanklosko/groupifier#11]
During the running of a competition I was organizing, We added a round of 6x6 near the end of day one as we were running ahead of schedule. This was not planned before the competition and was not in the schedule, so when it came on the second day to begin to print round 2 scorecards for the events running that day, we were faced with Groupifier not being able to assign groups. 

As this was during the competition I have no record of what it exactly said, but the issue ultimately was that it wouldn't assign groups without the extra round being added to the schedule on the WCA. 

What I am wondering is if there is a way to be prompted if this is the problem, or what the problem is if Groupifier fails to assign groups or tasks, which to somebody not familiar with the system may have great trouble figuring out.

Thanks.

**Comment by jonatanklosko** [comment]
Groupifier requires all the rounds to be present in the schedule as well (because groups are actually sub-activities of the given round in the schedule). When you add a round on the WCA website without including it in the schedule, Groupifier shows an error like "No schedule activities for <round>.", which means you have to add the given round to the schedule.
All of that is expected so I'm closing the issue, if you have an idea for a more clear message let me know!
