### ISSUE TITLE
Groups don't reflect the configuration options (at least with a low competitor count)

### ISSUE THREAD

**Issue by tnorr** [jonatanklosko/groupifier#14]
I tried groupifier for the first time last week but in its current state I don't think it helped with anything. I see there is an "assign tasks only in events competitors registered for" option. It would be nice but just if it changed anything.

I had 13 events and competitors that registered for only 3x3 were mainly assigned 8 or 10 tasks in total! Meanwhile there were a few competitors participating in around 11 events and having just 6 tasks assigned. This is really unfair for the competitors and doesn't help at all with organizing since most likely the former are not even at the venue to do the 10 tasks they should. After all I tried many different configurations but always got similar groups.

Is this how it should go? I had 2 groups in all events and tapping the option I mentioned I would assume that at least the general trend would be "compete in one group, staff in another". I don't know if this is handled better when there are more competitors/groups but I see this as a problem.

**Comment by jonatanklosko** [comment]
Hey there, I assume you talk about Tapiola Winter Open 2019 and I see that you manually specified roles in the `Edit roles` section (marking people as `judge`, `scrambler`, etc). Doing so means the usual rules don't apply, because those people are considered to be "staff" and prioritized in task assignment. Specifically the options you mentioned are also not taken into account for "staff" members.

In general you want to use the roles editor only when there's a group of people who are supposed to do all the tasks, otherwise Groupifier does its best to figure out best assignment scheme.

As there's no particular issue here I'm gonna close it, but if you have any doubts/further questions let me know!

**Comment by Goosly** [comment]
I did not assign any roles and get stuff like this with "Assign tasks to competitors only in events they registered for" checked.

![image](https://user-images.githubusercontent.com/12575384/71579194-c3e5da00-2afb-11ea-9912-737e7c3c903a.png)

**Comment by jonatanklosko** [comment]
This is expected ^^ The option you mentioned (as any other) is not *strict*, in the sense that Groupifier prefers to "break the rules" instead of leaving a round with insufficient amount of judges/scrambler. On your screenshot there's definitely the right tendency of assigning tasks in one's events only, but taking square for instance, it requires `13 judges + 2 scramblers + 2 runners = 17 helpers`, whereas the first/second group has only `13` participants, so when one group competes there are not enough people satisfying the rule and that's why others are assigned to help.

Usually when you see stuff like that it most likely means the conditions don't allow for a "perfect" assignment. As another example, if you use "Don't assign tasks to newcomers" and have a lot of newcomers, you limit the group of potential helpers significantly, so others get a lot of tasks and some newcomers may still be needed for help.

**Comment by Goosly** [comment]
Well, I'm sure there are a lot of organizers and delegates that use the "compete in one group, staff in another" approach, as @tnorr mentioned, and apparently there is no way to have this, even though the user is tricked into believing there is

In the example of my competition, the sq1 groups don't need 13 judges when there are 13 competitors... Just 8 or something would be enough

**Comment by jonatanklosko** [comment]
> Well, I'm sure there are a lot of organizers and delegates that use the "compete in one group, staff in another" approach, as @tnorr mentioned, and apparently there is no way to have this, even though the user is tricked into believing there is

Well, having more stations than competitors is a relatively rare case and for any other rule it's usually possible to figure out a scenario when it cannot be satisfied. We could change the wording to say "Prefer assigning ..." or whatever, but I'm not sure if it brings any value and using it for many options would be kinda redundant.

> In the example of my competition, the sq1 groups don't need 13 judges when there are 13 competitors... Just 8 or something would be enough

Normally Groupifier assigns one judge per timing station and in case of less competitors than timing stations it assigns one for each competitor. I get that in some cases that many are not necessary, but in others it's kinda handy to have everyone sitting with a judge (especially during finals).
