### ISSUE TITLE
Groupifier doesn't allow you to access a competition whatsoever if an event isn't on the WCA schedule

### ISSUE THREAD

**Issue by maconard** [jonatanklosko/groupifier#19]
We had to cancel 4x4x4 because of organizer error. We elected to keep it on the event list just in case we found time to hold it, but removed it from the schedule for the schedule to be accurate.

Following that and synchronizing WCA Live, groupifier is no longer usable because "4x4x4 is not scheduled."

I'd propose having this warning is okay, but the event should then be ignored and groupifier should be able to work for all the scheduled events.

Cheers

**Comment by jonatanklosko** [comment]
Honestly, this is the first case of the error not being entirely appropriate and as you said it was because of a planning error, so I believe making the warning optional could be more harmful than helpful. Also in general it's just invalid to have rounds and not have schedule activities, the WCA website does even validate that on competition confirmation request. Normally removals of an event would be handled before the competition and if the event cannot be held, it may as well be removed after the competition.
