### ISSUE TITLE
Access for score-takers

### ISSUE THREAD

**Issue by AlexKatyukov** [jonatanklosko/groupifier#3]
Groupifier is integrated with WCA Live very deep. For example, if I assign "Data Entry" task to competitor, he will can manage competition in WCA Live using his WCA account. But there is no scorecard printing at WCA Live. I need to go to Groupifier to print scorecards. But score-taker have not access to competition in Groupifier. I suggest to provide access to people with "Data Entry" role (maybe only for scorecards printing).
_It's not so important: organizer can sign in to WCA Website, open Groupifier and sign out from WCA Website, but it's a little tricky._

**Comment by jonatanklosko** [comment]
Actually it's not really Groupifier that restricts the permissions here, it's the WCA website (only organizers and delegates can load and modify competition data over the API). Also as explained [here](https://github.com/thewca/wca-live/issues/7#issuecomment-533878791), currently we believe that scoretakers shouldn't necessarily have more rights than just doing the detaentry (they are admins on WCA Live, but this effectively makes them able to just do dataentry tasks, nothing more).
This is still a subject for discussion and you can find more details [here](https://docs.google.com/document/d/18OLajbUZ1C_NPvI_geO8oX0rV2aWjxkETGsWwSh53r4/edit), but since it has to do with the WCA website and not Groupifier, I'm gonna close this one.
