### ISSUE TITLE
manage groups - additional functionality

### ISSUE THREAD

**Issue by WilhelmKilders** [jonatanklosko/groupifier#4]
Hi,

I very happy to see the groupifier is getting new features.
Regarding the manage groups feature I would love to have the option to add/remove competitors from their respective tasks (competing, scrambling etc.). Unless I'm missing something, this doesn't seem to be possible right now.
I would imagine 1-2 additional collums showing the remaining competitors participating in this event but without a task and competitors not competing in this event and without any tasks from which you could move the people to the collums with the open tasks would be easiest. This way one could manually assign tasks to competitors. 
There would need to be a check in the background for each round of an event looking for competitors that were manually removed from one group that are currently in no other group participating even though they have registered for this event or you wouldn't enable to change the competitors groups.

Or this there an easy alternative already implemented that can be used to do this?

Best,
Wilhelm

**Comment by jonatanklosko** [comment]
You are right that currently there's not way to manually tweak the generated assignments. The idea of a assignments editor came up quite some time ago, it is a pretty complex feature though. The app shouldn't allow leading to an invalid state, and when you think about simultaneous events, existing task assignments, etc., it quickly becomes a whole lot of scenarios. I hope I'll find enough time to implement it properly.

**Comment by WilhelmKilders** [comment]
Hmm I see, I haven't thought about simultaneous events. I get your point that you want to implement it properly. 
This is a bummer..I guess most competitions don't have simultaneous events but might need tweaking in the assignment. 
Would it be easier if one could only dismiss the selected scrabmler/judge/runner and the app would search for another option?

How would you go about if for example you find the app selects a scrambler that might not be as reliable as you would hope or has been selected too often already? Because I currently don't have a proper solution in mind?

Btw. what would be the usual way to select scramblers/judges for subsequent rounds? I guess the app right now can only generate those when the first round is already done, right? Is there anything planned that lets you pick scramblers/judges/runners in advance for all rounds and groups? This would be handy to inform people in advance so they will be present once the round happens.

**Comment by jonatanklosko** [comment]
I'd rather defer it until I have a good functionality in mind rather than spending time on the specific and limited dismiss feature ^^

> How would you go about if for example you find the app selects a scrambler that might not be as reliable as you would hope or has been selected too often already? Because I currently don't have a proper solution in mind?

Well, if you mark people as scrambles in the roles editor (if you have staff) then you obviously get reliable scramblers. Otherwise Groupifier does its best to pick proper scramblers, by choosing the best people in the given event (when combined with Balanced/Symmetric sorting this ensures good 
scramblers for every group). It get that there may be specific scenarios where this heuristic fails, but I wouldn't expect this to be the case often.

> Btw. what would be the usual way to select scramblers/judges for subsequent rounds? I guess the app right now can only generate those when the first round is already done, right? Is there anything planned that lets you pick scramblers/judges/runners in advance for all rounds and groups? This would be handy to inform people in advance so they will be present once the round happens.

That's correct, assigning tasks for further rounds is done at the same time as further groups, so once the first round results are there. Picking people in advance is tricky, as there's no way to exactly predict in which group the given person will end up. Groupifier generally tries to assign people who are likely to be at the venue (around the time they compete). I don't really have any feedback on further round assignments, as this has only been enabled recently (by entering results in WCA Live), will see how it goes.

**Comment by WilhelmKilders** [comment]
Ok, I see.
Thank you very much for your feedback!

**Comment by jonatanklosko** [comment]
I've finally implemented that, you can now manually edit all the assignments!

![image](https://user-images.githubusercontent.com/17034772/73771955-971e8580-477f-11ea-9f8f-79a9d3c174a0.png)
