### ISSUE TITLE
Allow for different # of scrambling stations/scramblers per event.

### ISSUE THREAD

**Issue by KitClement** [jonatanklosko/groupifier#4]
In practice, it's fairly common to have a different number of scramblers depending upon the event. For example, bigger cubes may need more scramblers due to the time needed to scramble. Events like 3BLD often use fewer scramblers. 

Less popular events may also use fewer stations too. Long rooms also don't really fit the "station" structure as well.

Currently, this could be patched in by creating a different CSV for each event, and then combining all of the exports together, but this would not create appropriate personal cards.

**Comment by jonatanklosko** [comment]
Agreed, this is something worth taking into account. Something relatively simple would be allowing for any positive scramblers count when you use the manual selection (at the moment the exact number is enforced), would that make sense? A more flexible solution allowing for manual assignment would be asking do enter the data for each event.

Concerning the stations count, what kind of scenario do you think of? Is it like 3x3 on the main stage and 7x7 as a side event being held simultaneously (in that case the simultaneous events feature could be used), where the station counts differ? Or do you have another case in mind in particular?

> Long rooms also don't really fit the "station" structure as well.

What exactly do you mean by that?

**Comment by KitClement** [comment]
I know for our local competitions, blindfolded events (even 3x3) often do not use all of the stations.

As for the long room type events, there's not typically the same flow as there would be for an event like 3x3. We typically use a classroom setup of tables where there are floating judges watching all of the competitors at once. There's not really a fixed number of stations because we usually just have people enter/exit the table area as they do solves.

Maybe the simpler idea is to not ask for stations, but to ask for how many competitors per group? It looks like the program is aiming for roughly 1.5*stations competitors per group. Personally, I like to put more in a group than this number, but it really depends on the speed of the event and the cutoffs used.

I like the idea of asking for this by event rather than having it be a global setting.

**Comment by jonatanklosko** [comment]
Which events do you have in mind when describing the long room system?

Asking for the number of competitors per group for each events is basically that I've been aiming to avoid since the very beginning. The main philosophy is to let the user enter some **facts** (simple data), just like the stations count, and handle all the logic and thinking for him (which tries to minimize the user's effort and possible errors). I realise that there are always some scenarios that don't feet perfectly, but I'd rather put an effort into improving the way groups count is determined.
It is currently done like so (see the comments) https://github.com/jonatanklosko/groupifier/blob/8139bb32cbca1ba296c257bf3b47c0e3d4247563/src/groups-assignment.js#L158-L169

**Comment by Mollerz** [comment]
I think it'd be nice if there was an option to enter more detail if necessary. I completely understand the philosophy of it being fully automated and I definitely think this should be the goal as often as possible. But bigger competitions and more complex schedules still require something like Groupifier - as manually doing everything is an enormous hassle, so even automating a portion of it using familiar software is good.

Maybe there should be an "Advanced Groupifier" box that you can check that allows you to go further and customise things like different number of timers/scramblers per group etc. for when needing those extra options really is a requirement. So that once you press "Generate" it takes you through to a secondary page which lets you make any small adjustments you might want?

**Comment by jonatanklosko** [comment]
Closing as this tool is now deprecated in favor of more powerful [groupifier-next](https://github.com/jonatanklosko/groupifier-next). Also this feature is one of the key points of groupifier-next!
