### ISSUE TITLE
Group overview fails to download when selecting second/third/etc.. rounds

### ISSUE THREAD

**Issue by louismeunier** [jonatanklosko/groupifier#46]
I've been trying to download the group overview sheet for Empire Spring 2022, and while it properly downloads when only the first rounds of events are selected, nothing happens when second rounds and finals are selected as well. Looking at the console, the following error is also printed.
<img width="333" alt="Screen Shot 2022-04-30 at 6 30 07 AM" src="https://user-images.githubusercontent.com/64540985/166102004-3815205b-7ca9-42c0-aaf5-c3dabfc4ee25.png">

**Comment by jonatanklosko** [comment]
To clarify, this happens because the subsequent rounds don't have any competitors yet, once the second round opens and you create groups, it should work fine. Note that the subsequent rounds are grayed out, but you can still select them when downloading scorecards (to get empty scorecards). For group overview there's nothing to show for those rounds.

That said, we definitely shouldn't emit the error! I've just fixed this in 29f85e6fa8db4e4ae964ada7823c3b62673100cf, thanks for the report :)

**Comment by louismeunier** [comment]
I believe when I've printed group overviews in the past, however, they at least showed the time that subsequent rounds started & ended, despite obviously not having any actual groups set yet.

**Comment by jonatanklosko** [comment]
It would've worked if it was the first round without groups, or a subsequent group with advanced competitors but without groups.

**Comment by louismeunier** [comment]
Ah I see, I understand. Thanks for the clarification.
