### ISSUE TITLE
Number of Groups doesn't Synchronize with WCA Website

### ISSUE THREAD

**Issue by mihlefeld** [jonatanklosko/groupifier#54]
When changing the number of scramble sets on the WCA website and then synchronizing on WCA live, groupifier does not apply the changes to the number of groups. This means that we have to manually change everything to match with the WCA site.

**Comment by jonatanklosko** [comment]
Hey @mihlefeld :)

This is expected, Groupifier assumes it is the one controlling groups, it actually sets the number of scramble sets on the WCA website when you create groups (that's mostly for convenience). I don't think Groupifier should automatically make changes when the number of scramble sets changes on the WCA website, because there is much more configuration involved in creating and assigning groups (the user can even manually adjust assignments, and we don't want to automatically override their work).

It is generally best to use Groupifier after registration, when you know the number of groups. If this needs to updated, you need to reset assignments in Groupifier, change the number of groups in the configuration, then create assignments again (which will also update the number of scramble son the WCA website).
