### ISSUE TITLE
Individual sorting of groups by event

### ISSUE THREAD

**Issue by WilhelmKilders** [jonatanklosko/groupifier#63]
When creating the grouping for the first rounds it would be very helpful if you could select for each event individually how you want to sort the competitors. So for example you could select Skewb, Clock, 2x2, 3x3 and OH to be sorted by speed and 4x4-7x7 to be optimised for scrambling. 

I know that the option balanced tries to do this but it doens't sort all scramble dependend puzzles by speed (i.e. Clock, SQ-1 and OH).
For some of those events it's not uncommon to only hold one round at a comp where you should definitely have all the fast people receiving the same scrambles. 
Of course you can sort the people by hand but it gets messy quickly if you have more than two groups to go through for multiple events.

If would love to see this feature added since the scrambler optimised grouping is really nice :).

Best,
Wilhelm

**Comment by jonatanklosko** [comment]
I would be ok with switching Clock and SQ-1 so that balanced sorts them by speed (OH already is). When I was building Groupifier those two events were not as developed as they are now (e.g. in case of clock, the cubes were not as good, so inexperienced scrambles were much more prone to mistakes). Let me know if that works for you.

Configuring this per-event is doable, but it is a more involved change and at this point I rather try to maintain the tool than introduce new features :)

**Comment by WilhelmKilders** [comment]
Thanks for the quick response!
Yes, this would be very helpful and the German organisers would much appreciate it :). 
I guess I must have missed that all 3x3 variations already get sorted by speed; my bad.
However I noticed that 3BLD gets sorted by mean. Maybe single makes more sense here since the format is Bo3 mostly and not all fast 3BLDers have means already (for example: https://www.worldcubeassociation.org/persons/2019LENS01)

**Comment by jonatanklosko** [comment]
I made the change for balanced, and changed sorting for BLD events to sort by single first :)
