### ISSUE TITLE
JSON export missing

### ISSUE THREAD

**Issue by druidalek** [jonatanklosko/groupifier#7]
I can see the "Export people as JSON" is missing from the newer version. Is this intentional? I'm building a mini-project which allows us to display each group with it's competitors, judges, scrambers, etc on a visual screen live during the competition. In order to do this I created an interface for importing and sorting people into rounds and groups. Meanwhile, I found out that the JSON export from the final groupifier groups will work perfectly. 

However, I see that the new version doesn't have that feature.

**Comment by jonatanklosko** [comment]
Yeah, that's intentional. The reason for no export is that we (the WST) designed a standardized competition data format ([WCIF](https://github.com/thewca/wca-live/blob/master/docs.md#wording)) and Groupifier works with it as well. Everything you generate gets saved back to the WCA website, and can be loaded via the API (at this point this API requires authorization, so you need to be either a delegate or an organizer, but we plan to enable a public version of it, see https://github.com/thewca/worldcubeassociation.org/issues/4640). The idea is for many tools to work with the established WCIF format and persist it to the WCA website, instead of depending on some specific export format.

Let me know if you have any further questions to that =)
